ci(semantic-release): configure Semantic Release
- Ajout du job `Release` dans le workflow GitHub Actions pour la CI
- Ajout du script de génération d'archive ZIP de l'artifact

fix #46

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -96,7 +96,7 @@ jobs:
           name: coverage-report
           path: ./coverage # L'artefact sera téléchargé dans le dossier './coverage'
 
-      # Étape 4 : Vérifier l'existance de secrets.SONAR_TOKEN
+      # Étape 4 : Vérifier l'existence de secrets.SONAR_TOKEN
       - name: Verify Sonar Token
         run: |
           if [[ -z "${{ secrets.SONAR_TOKEN }}" ]]; then
@@ -109,3 +109,45 @@ jobs:
         uses: SonarSource/sonarqube-scan-action@v4.2.1 # Utilisation de l'action officielle de SonarQube
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Utilisation du token secret pour SonarCloud
+
+  # Job de release avec Semantic Release
+  release:
+    name: Release
+    runs-on: ubuntu-latest
+    needs: [build-lint-test, sonarqube] # Exécuter après les jobs de test et d'analyse
+    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
+
+    steps:
+      # Étape 1 : Récupérer le code source
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # Nécessaire pour récupérer tous les tags et commits
+
+      # Étape 2 : Installer Node.js
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version-file: .nvmrc
+
+      # Étape 3 : Installer les dépendances via npm
+      - name: Install dependencies
+        run: npm ci
+
+      # Étape 4 : Vérifier l'existence de GITHUB_TOKEN
+      - name: Verify GitHub Token
+        run: |
+          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then
+            echo "❌ ERROR: GITHUB_TOKEN is missing!"
+            exit 1
+          fi
+
+      # 5. Exécuter le build
+      - name: Build project
+        run: npm run build
+
+      # Étape 6 : Exécuter Semantic Release
+      - name: Run Semantic Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: npx semantic-release
